language: go
go_import_path: github.com/google/go-cloud
go: "1.10.x"
install:
  - "go get -u golang.org/x/vgo"
  - "go get -u github.com/golangci/golangci-lint/cmd/golangci-lint"
script:
  # TRAVIS_PULL_REQUEST is set to "false" for branch builds, and the PR number
  # for pull request builds. Branch builds should test everything.
  - 'if [[ "$TRAVIS_PULL_REQUEST" != false ]]; then testing/checkpr.sh -short -race; else vgo test -short -race ./...; fi'
  - "vgo vendor"
  - "golangci-lint run --new-from-rev=\"$TRAVIS_BRANCH\" --print-welcome=false --disable=varcheck $(find . -type d ! -path \"./.git*\" ! -path \"./tests*\" ! -path \"./vendor*\" ! -path \"./wire/internal/wire/testdata*\" ! -path \"*_demo*\")"
