os:
  - linux
  - osx

language: go

before_install:
  # The Bash that comes with OS X is ancient.
  # checkpr.sh needs Bash 4. It's OK to not worry about this issue for
  # customers as checkpr.sh is only for running on Travis.
  # grep is similar: it's not GNU grep, which means commands aren't portable.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      HOMEBREW_NO_AUTO_UPDATE=1 brew install bash; 
      HOMEBREW_NO_AUTO_UPDATE=1 brew install grep --with-default-names;
    fi

install:
  - "go get -u golang.org/x/vgo"
  - "go get -u github.com/golangci/golangci-lint/cmd/golangci-lint"

script:
  # TRAVIS_PULL_REQUEST is set to "false" for branch builds, and the PR number
  # for pull request builds. Branch builds should test everything.
  - 'if [[ "$TRAVIS_PULL_REQUEST" != false ]]; then testing/checkpr.sh -short -race; else vgo test -short -race ./...; fi'
