language: go
go_import_path: github.com/google/go-cloud
go: "1.10.x"
install:
  - "go get -u golang.org/x/vgo"
script:
  - 'if [[ "$TRAVIS_PULL_REQUEST" != false ]]; then testing/checkpr.bash -short -race; else vgo test -short -race ./...; fi'
