language: go
go_import_path: github.com/google/go-cloud
go: "1.10.x"
install:
  - "go get -u golang.org/x/vgo"
  - "go get -u github.com/golangci/golangci-lint/cmd/golangci-lint"
script:
  - "vgo test -short -race ./..."
  # Vendoring is required for the linter to be able to understand the workspace.
  - "vgo vendor"
  - "golangci-lint run $(find . -type d ! -path \"./.git*\" ! -path \"./tests*\" ! -path \"./goose/internal/goose/testdata*\" ! -path \"*_demo*\")" 
