os:
  - linux
  - osx

language: go
go_import_path: github.com/google/go-cloud
# Travis has Go 1.9 on Mac OS X. That should be OK for us.
# TODO(cflewis): File a bug against Travis.
go: "1.9.x"
before_install:
  # The Bash that comes with OS X is ancient.
  # checkpr.sh needs Bash 4. It's OK to not worry about this issue for
  # customers as checkpr.sh is only for us to run on Travis.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      HOMEBREW_NO_AUTO_UPDATE=1 brew install bash;
      export PATH=$(brew --prefix)/bin:$PATH; 
    fi
install:
  - "go get -u golang.org/x/vgo"
  - "go get -u github.com/golangci/golangci-lint/cmd/golangci-lint"
script:
  # TRAVIS_PULL_REQUEST is set to "false" for branch builds, and the PR number
  # for pull request builds. Branch builds should test everything.
  - 'if [[ "$TRAVIS_PULL_REQUEST" != false ]]; then testing/checkpr.sh -short -race; else vgo test -short -race ./...; fi'
