os:
  - linux
  # Travis has Go 1.10 on Mac OS X. That's not OK, vgo needs 1.10.
  # Bug filed as https://github.com/travis-ci/travis-ci/issues/9775
  # - osx

language: go
before_install:
  # The Bash that comes with OS X is ancient.
  # checkpr.sh needs Bash 4. It's OK to not worry about this issue for
  # customers as checkpr.sh is only for us to run on Travis.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      HOMEBREW_NO_AUTO_UPDATE=1 brew install bash;
      export PATH=$(brew --prefix)/bin:$PATH; 
    fi
install:
  - "go get -u golang.org/x/vgo"
  - "go get -u github.com/golangci/golangci-lint/cmd/golangci-lint"
script:
  # TRAVIS_PULL_REQUEST is set to "false" for branch builds, and the PR number
  # for pull request builds. Branch builds should test everything.
  - 'if [[ "$TRAVIS_PULL_REQUEST" != false ]]; then testing/checkpr.sh -short -race; else vgo test -short -race ./...; fi'
