runtime: go111
env_variables:
  DB_USER: guestbook
  DB_INSTANCE: gocloudgae:us-central1:go-guestbook-5e062e6ae12e1d19c3a9293bb6059e9e
  DB_DATABASE: guestbook
  DB_PASSWORD: lquKspF8ig1YWlGHeuPi
  GUESTBOOK_BUCKET: go-guestbook-60c994ce520b7ccfcc4445b941a9392b

